version: '2'
services:
  proxyway:
    container_name: proxyway
    image: nginx:1.11.4-alpine
    ports:
      - "8081:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      rdb:
        aliases:
          - proxyway.nginx
    depends_on:
      - api1
      - api2
      - api3

  api1:
    container_name: api1
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      rdb:
        aliases:
          - api1.api
    command: "pm2 start --no-daemon ./app/index.js -i max --watch"
    environment:
      RETHINK_HOST: rdb1.rdb
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  api2:
    container_name: api2
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      rdb:
        aliases:
          - api2.api
    command: "pm2 start --no-daemon ./app/index.js -i max --watch"
    environment:
      RETHINK_HOST: rdb2.rdb
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  api3:
    container_name: api3
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      rdb:
        aliases:
          - api3.api
    command: "pm2 start --no-daemon ./app/index.js -i max --watch"
    environment:
      RETHINK_HOST: rdb3.rdb
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  # https://github.com/docker/notary/blob/master/docker-compose.rethink.yml
  # https://nathanleclaire.com/blog/2015/11/17/seamless-docker-multihost-overlay-networking-on-digitalocean-with-machine-swarm-and-compose-ft.-rethinkdb/
  rdb1:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb1:/var/data
    networks:
      rdb:
        aliases:
          - rdb1.rdb
    ports:
      - "8080:8080"
    command: "--bind all --server-name rdb1 --canonical-address rdb1.rdb --directory /var/data/rethinkdb"

  rdb2:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb2:/var/data
    networks:
      rdb:
        aliases:
          - rdb2.rdb
    command: "--bind all --no-http-admin --server-name rdb2 --canonical-address rdb2.rdb --directory /var/data/rethinkdb --join rdb1"
    depends_on:
      - rdb1

  rdb3:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb3:/var/data
    networks:
      rdb:
        aliases:
          - rdb3.rdb
    command: "--bind all --no-http-admin --server-name rdb3 --canonical-address rdb3.rdb --directory /var/data/rethinkdb --join rdb2"
    depends_on:
      - rdb1
      - rdb2

networks:
  rdb:
    external: false
