version: '2'
services:
  proxyway:
    container_name: proxyway
    image: nginx:1.11.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - apinet
    depends_on:
      - api1
      - api2
      - api3

  api1:
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      - apinet
    command: "./node_modules/.bin/pm2-docker /src/pm2process.yml"
    environment:
      RETHINK_HOST: rdb1
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  api2:
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      - apinet
    command: "./node_modules/.bin/pm2-docker /src/pm2process.yml"
    environment:
      RETHINK_HOST: rdb2
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  api3:
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    image: catchalong-api
    volumes:
      - ./../:/src
    networks:
      - apinet
    command: "./node_modules/.bin/pm2-docker /src/pm2process.yml"
    environment:
      RETHINK_HOST: rdb3
    depends_on:
      - rdb1
      - rdb2
      - rdb3

  # https://github.com/docker/notary/blob/master/docker-compose.rethink.yml
  # https://nathanleclaire.com/blog/2015/11/17/seamless-docker-multihost-overlay-networking-on-digitalocean-with-machine-swarm-and-compose-ft.-rethinkdb/
  rdb1:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb1:/var/data
    networks:
      apinet:
      dbnet:
        aliases:
          - rdb.1
    ports:
      - "8081:8080"
    command: "--bind all --canonical-address rdb.1 --directory /var/data/rethinkdb"

  rdb2:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb2:/var/data
    networks:
      apinet:
      dbnet:
        aliases:
          - rdb.2
    command: "--bind all --no-http-admin --canonical-address rdb.2 --directory /var/data/rethinkdb --join rdb.1"
    depends_on:
      - rdb1

  rdb3:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.jlhawndata/rdb3:/var/data
    networks:
      apinet:
      dbnet:
        aliases:
          - rdb.3
    command: "--bind all --no-http-admin --canonical-address rdb.3 --directory /var/data/rethinkdb --join rdb.2"
    depends_on:
      - rdb1
      - rdb2

networks:
  apinet:
    external: false
  dbnet:
    external: false
